########################################################################################################################
## SPRING ##############################################################################################################
########################################################################################################################

spring.application.name: Counter
server.port: 10002

eureka.client.serviceUrl.defaultZone: http://localhost:10000/eureka
eureka.client.register-with-eureka: true
eureka.client.fetch-registry: true

logging.level.com.rubenjg: DEBUG
logging.level.com.netflix.eureka: DEBUG
logging.level.com.netflix.discovery: DEBUG
